apiVersion: apps/v1
kind: Deployment
metadata:
  name: site-service-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: site-service
  template:
    metadata:
      labels:
        app: site-service
    spec:
      containers:
        - name: site-service
          image: site-service-image
          ports:
            - containerPort: 8082
