apiVersion: apps/v1
kind: Deployment
metadata:
  name: organization-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: organization-service
  template:
    metadata:
      labels:
        app: organization-service
    spec:
      containers:
        - name: organization-service
          image: organization-service-image
          ports:
            - containerPort: 8083
